### ISSUE TITLE
Change Readme.md 

### ISSUE THREAD

**Issue by christopheralex** [UBC-MDS/contraceptive_method_predictor#77]
We use Python 3.9.7. There is a different version mentioned in README.md

**Comment by christopheralex** [comment]
> We use Python 3.7.3 and Python packages for analysis. For details, please refer to env-cmp.yaml.

**Comment by abhiket** [comment]
added about knitr and kable

**Comment by harryyikhchan** [comment]
Done in #82. And change to Python 3.9.5 as the default version according to the installation instruction
